# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3874b80bb1ac5ccbc674a8bc7db2cdd12047740112f44696c3bfa5809d39c2507e6ae3f4a03c9f32e0f45362e86c598204fac9d89ac96362dda26354d00c4fc4

test:
  secret_key_base: 57c2c4001c96f703719b20a659777fd97acfb13a799a88ceb1fa2231ea88a87f837d7e7c3b9a050e27eca48010bef36d4450a8fb11aee1a611bdc70614161571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
